/* client-tls-unknownext.c
 *
 * Copyright (C) 2006-2026 wolfSSL Inc.
 *
 * This file is part of wolfSSL. (formerly known as CyaSSL)
 *
 * wolfSSL is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * wolfSSL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 */

/* Demonstrates the certificate manager's unknown-extension callbacks.
 *
 * wolfSSL decodes the X.509 and CRL extensions it knows about. An extension it
 * does not recognize is ignored when non-critical and, per RFC 5280, rejected
 * when critical. An application that needs to see (and possibly accept) such
 * extensions registers a callback on the WOLFSSL_CTX's certificate manager:
 *
 *   wolfSSL_CertManagerSetUnknownExtCallback()    - certificate extensions
 *   wolfSSL_CertManagerSetCRLUnknownExtCallback() - CRL extensions
 *
 * This client loads ../certs/crl-idp/crl-idp.pem, a CRL carrying a critical
 * Issuing Distribution Point extension (OID 2.5.29.28) that wolfSSL does not
 * decode. Without a callback the CRL fails to load with ASN_CRIT_EXT_E (run
 * with "nocb" to see this). With the callbacks registered, wolfSSL hands the
 * extension to CrlUnknownExtCb() below, which accepts it, and the CRL loads.
 * The server certificate carries a matching CRL Distribution Points extension
 * and is checked against that CRL during the handshake.
 *
 * wolfSSL must be built with CRL support and the unknown-extension callback:
 *   ./configure --enable-crl CFLAGS="-DWOLFSSL_CUSTOM_OID -DHAVE_OID_DECODING"
 *
 * Certificates and the CRL are generated by ../certs/crl-idp/gen-crl-idp.sh.
 * Run against server-tls-unknownext.
 */

/* the usual suspects */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

/* socket includes */
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <unistd.h>

/* wolfSSL */
#include <wolfssl/options.h>
#include <wolfssl/ssl.h>

#define DEFAULT_PORT 11111

#define CA_FILE  "../certs/crl-idp/ca-cert.pem"
#define CRL_FILE "../certs/crl-idp/crl-idp.pem"

#if defined(HAVE_CRL) && defined(WC_ASN_UNKNOWN_EXT_CB)

/* id-ce-issuingDistributionPoint, RFC 5280 section 5.2.5 */
static const word16 idpOid[] = { 2, 5, 29, 28 };

static int OidMatches(const word16* oid, word32 oidSz,
                      const word16* want, word32 wantSz)
{
    return (oidSz == wantSz) &&
           (memcmp(oid, want, wantSz * sizeof(word16)) == 0);
}

/* Called for every extension wolfSSL does not recognize.
 *
 *   where      : which callback it arrived through (see the wrappers below)
 *   oid, oidSz : the extension's OID as an array of arcs, e.g. {2,5,29,28}
 *   crit       : non-zero when the extension is marked critical
 *   der, derSz : the DER inside the extension's OCTET STRING, not decoded
 *
 * Return 0 to accept the extension. Return a negative value to reject it, which
 * makes the certificate or CRL it came from fail to parse. The callback runs
 * before the signature on the certificate/CRL has been checked, so treat
 * der/derSz as untrusted input. */
static int UnknownExtCb(const char* where, const word16* oid, word32 oidSz,
                        int crit, const unsigned char* der, word32 derSz)
{
    word32 i;

    printf("Unknown %s extension: OID ", where);
    for (i = 0; i < oidSz; i++) {
        printf("%s%u", (i > 0) ? "." : "", oid[i]);
    }
    printf(", %scritical, %u bytes of DER\n   ", crit ? "" : "non-", derSz);
    for (i = 0; i < derSz; i++) {
        printf(" %02x", der[i]);
        if ((i % 20) == 19 && (i + 1) < derSz) {
            printf("\n   ");
        }
    }
    printf("\n");

    if (OidMatches(oid, oidSz, idpOid, sizeof(idpOid) / sizeof(idpOid[0]))) {
        /* Issuing Distribution Point. wolfSSL does not decode this extension,
         * so by accepting it this application takes on its semantics: an IDP
         * can narrow what the CRL covers (onlyContainsUserCerts,
         * onlySomeReasons, indirectCRL, ...). A real application would decode
         * 'der' here and honor those fields. */
        printf("    -> Issuing Distribution Point (RFC 5280 5.2.5): "
               "accepting\n");
        return 0;
    }

    if (crit) {
        /* Keep wolfSSL's default for anything else that is critical and
         * unknown: reject it. */
        printf("    -> unrecognized critical extension: rejecting\n");
        return -1;
    }

    printf("    -> non-critical: accepting\n");
    return 0;
}

/* Registered with wolfSSL_CertManagerSetUnknownExtCallback(). Invoked for
 * unknown extensions in certificates the certificate manager parses: CA
 * certificates loaded with wolfSSL_CTX_load_verify_locations() and buffers
 * passed to wolfSSL_CertManagerVerifyBuffer(). The CA certificate used here
 * has no unknown extensions, so this stays quiet in this example. */
static int CertUnknownExtCb(const word16* oid, word32 oidSz, int crit,
                            const unsigned char* der, word32 derSz)
{
    return UnknownExtCb("certificate", oid, oidSz, crit, der, derSz);
}

/* Registered with wolfSSL_CertManagerSetCRLUnknownExtCallback(). Invoked for
 * unknown extensions in CRLs, both CRL-level and per-revoked-entry. This is
 * the one the Issuing Distribution Point in crl-idp.pem reaches. */
static int CrlUnknownExtCb(const word16* oid, word32 oidSz, int crit,
                           const unsigned char* der, word32 derSz)
{
    return UnknownExtCb("CRL", oid, oidSz, crit, der, derSz);
}


int main(int argc, char** argv)
{
    int                sockfd;
    struct sockaddr_in servAddr;
    char               buff[256];
    size_t             len;
    int                ret;
    int                err;
    int                useCb;

    /* declare wolfSSL objects */
    WOLFSSL_CTX*          ctx = NULL;
    WOLFSSL*              ssl = NULL;
    WOLFSSL_CERT_MANAGER* cm;



    /* Check for proper calling convention */
    if (argc < 2 || argc > 3 || (argc == 3 && strcmp(argv[2], "nocb") != 0)) {
        printf("usage: %s <IPv4 address> [nocb]\n", argv[0]);
        printf("  nocb: skip registering the callbacks, so the CRL's critical "
               "Issuing\n        Distribution Point extension makes the CRL "
               "load fail\n");
        return 0;
    }
    useCb = (argc == 2);

    /* Create a socket that uses an internet IPv4 address,
     * Sets the socket to be stream based (TCP),
     * 0 means choose the default protocol. */
    if ((sockfd = socket(AF_INET, SOCK_STREAM, 0)) == -1) {
        fprintf(stderr, "ERROR: failed to create the socket\n");
        ret = -1;
        goto end;
    }

    /* Initialize the server address struct with zeros */
    memset(&servAddr, 0, sizeof(servAddr));

    /* Fill in the server address */
    servAddr.sin_family = AF_INET;             /* using IPv4      */
    servAddr.sin_port   = htons(DEFAULT_PORT); /* on DEFAULT_PORT */

    /* Get the server IPv4 address from the command line call */
    if (inet_pton(AF_INET, argv[1], &servAddr.sin_addr) != 1) {
        fprintf(stderr, "ERROR: invalid address\n");
        ret = -1;
        goto end;
    }

    /* Connect to the server */
    if ((ret = connect(sockfd, (struct sockaddr*) &servAddr, sizeof(servAddr)))
         == -1) {
        fprintf(stderr, "ERROR: failed to connect\n");
        goto end;
    }

    /*---------------------------------*/
    /* Start of wolfSSL initialization and configuration */
    /*---------------------------------*/
    /* Initialize wolfSSL */
    if ((ret = wolfSSL_Init()) != WOLFSSL_SUCCESS) {
        fprintf(stderr, "ERROR: Failed to initialize the library\n");
        goto socket_cleanup;
    }

    /* Create and initialize WOLFSSL_CTX */
#ifdef USE_TLSV13
    ctx = wolfSSL_CTX_new(wolfTLSv1_3_client_method());
#else
    ctx = wolfSSL_CTX_new(wolfTLSv1_2_client_method());
#endif
    if (ctx == NULL) {
        fprintf(stderr, "ERROR: failed to create WOLFSSL_CTX\n");
        ret = -1;
        goto ctx_cleanup;
    }

    /* Get the certificate manager owned by the WOLFSSL_CTX. Everything the
     * context verifies (CA certificates, peer certificates, CRLs) goes through
     * it, so this is where the extension callbacks are registered. */
    cm = wolfSSL_CTX_GetCertManager(ctx);
    if (cm == NULL) {
        fprintf(stderr, "ERROR: failed to get the certificate manager\n");
        ret = -1;
        goto ctx_cleanup;
    }

    if (useCb) {
        /* Be told about unknown extensions in certificates ... */
        wolfSSL_CertManagerSetUnknownExtCallback(cm, CertUnknownExtCb);

        /* ... and in CRLs. */
        if ((ret = wolfSSL_CertManagerSetCRLUnknownExtCallback(cm,
                CrlUnknownExtCb)) != WOLFSSL_SUCCESS) {
            fprintf(stderr, "ERROR: failed to set the CRL extension "
                    "callback\n");
            ret = -1;
            goto ctx_cleanup;
        }
        printf("Registered unknown-extension callbacks\n");
    }
    else {
        printf("Not registering unknown-extension callbacks\n");
    }

    /* Load CA certificate into WOLFSSL_CTX */
    if ((ret = wolfSSL_CTX_load_verify_locations(ctx, CA_FILE, NULL))
         != WOLFSSL_SUCCESS) {
        fprintf(stderr, "ERROR: failed to load %s, please check the file.\n",
                CA_FILE);
        ret = -1;
        goto ctx_cleanup;
    }

    /* Check every certificate the peer presents against the loaded CRLs */
    if ((ret = wolfSSL_CTX_EnableCRL(ctx, WOLFSSL_CRL_CHECKALL))
         != WOLFSSL_SUCCESS) {
        fprintf(stderr, "ERROR: failed to enable CRL checking\n");
        ret = -1;
        goto ctx_cleanup;
    }

    /* Load the CRL. Its critical Issuing Distribution Point extension is
     * handed to CrlUnknownExtCb(); without that callback this fails with
     * ASN_CRIT_EXT_E. */
    if ((ret = wolfSSL_CTX_LoadCRLFile(ctx, CRL_FILE, WOLFSSL_FILETYPE_PEM))
         != WOLFSSL_SUCCESS) {
        fprintf(stderr, "ERROR: failed to load %s: %d (%s)\n", CRL_FILE, ret,
                wolfSSL_ERR_reason_error_string(ret));
        ret = -1;
        goto ctx_cleanup;
    }
    printf("Loaded %s\n", CRL_FILE);

    /* Create a WOLFSSL object */
    if ((ssl = wolfSSL_new(ctx)) == NULL) {
        fprintf(stderr, "ERROR: failed to create WOLFSSL object\n");
        ret = -1;
        goto ctx_cleanup;
    }

    /* Attach wolfSSL to the socket */
    if ((ret = wolfSSL_set_fd(ssl, sockfd)) != WOLFSSL_SUCCESS) {
        fprintf(stderr, "ERROR: Failed to set the file descriptor\n");
        goto cleanup;
    }

    /* Connect to wolfSSL on the server side. The server's certificate is
     * verified against CA_FILE and checked against the CRL; a server using
     * server-revoked-cert.pem fails here with CRL_CERT_REVOKED. */
    if ((ret = wolfSSL_connect(ssl)) != WOLFSSL_SUCCESS) {
        err = wolfSSL_get_error(ssl, ret);
        fprintf(stderr, "ERROR: failed to connect to wolfSSL: %d (%s)\n", err,
                wolfSSL_ERR_reason_error_string(err));
        goto cleanup;
    }
    printf("Connected; server certificate passed CRL check\n");

    /* Get a message for the server from stdin */
    printf("Message for server: ");
    memset(buff, 0, sizeof(buff));
    if (fgets(buff, sizeof(buff), stdin) == NULL) {
        fprintf(stderr, "ERROR: failed to get message for server\n");
        ret = -1;
        goto cleanup;
    }
    len = strnlen(buff, sizeof(buff));

    /* Send the message to the server */
    if ((ret = wolfSSL_write(ssl, buff, len)) != len) {
        fprintf(stderr, "ERROR: failed to write entire message\n");
        fprintf(stderr, "%d bytes of %d bytes were sent", ret, (int) len);
        goto cleanup;
    }

    /* Read the server data into our buff array */
    memset(buff, 0, sizeof(buff));
    if ((ret = wolfSSL_read(ssl, buff, sizeof(buff)-1)) == -1) {
        fprintf(stderr, "ERROR: failed to read\n");
        goto cleanup;
    }

    /* Print to stdout any data the server sends */
    printf("Server: %s\n", buff);

    /* Bidirectional shutdown */
    while (wolfSSL_shutdown(ssl) == WOLFSSL_SHUTDOWN_NOT_DONE) {
        printf("Shutdown not complete\n");
    }

    printf("Shutdown complete\n");

    ret = 0;

    /* Cleanup and return */
cleanup:
    wolfSSL_free(ssl);      /* Free the wolfSSL object                  */
ctx_cleanup:
    if (ctx)
        wolfSSL_CTX_free(ctx);  /* Free the wolfSSL context object      */
    wolfSSL_Cleanup();      /* Cleanup the wolfSSL environment          */
socket_cleanup:
    close(sockfd);          /* Close the connection to the server       */
end:
    return ret;               /* Return reporting a success               */
}

#else

int main(void)
{
    printf("Example requires wolfSSL built with --enable-crl and\n"
           "CFLAGS=\"-DWOLFSSL_CUSTOM_OID -DHAVE_OID_DECODING\"\n");
    return 0;
}

#endif /* HAVE_CRL && WC_ASN_UNKNOWN_EXT_CB */
